[package]
name = "config-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
once_cell.workspace = true
serde.workspace = true
salvo.workspace = true

seat-controller = { path = "../../seat/controller" }